### ISSUE TITLE
How to integrate programs not in Alpine package list

### ISSUE THREAD

**Issue by IOKG04** [IOKG04/h-e-l-l-o-w-o-r-l-d#10]
Haiiiii :3

I *maybe* wanna use some programs that are not in Alpines package list (here namely [unicc](https://github.com/phorward/unicc) maybe),
and seeing how I explicitly said I didn't want people to just include an existing projects source and add it to lengthen compilation,
wanted to ask how we wanna handle that.

My suggestion would be that we add a `src/setup.sh` that gets run by the docker container *on setup*.
It wouldn't increase build time, and still leave a good bit of freedom.

Open for other suggestions though, that's why I made this an issue instead of just deciding and pushing and having you all have to conform to my idea.

**Comment by IOKG04** [comment]
@zxcv05 since you're the only other person here, you gotta answer

**Comment by zxcv05** [comment]
Hello! A setup script would probably be the easiest solution, we could add it to the end of the Dockerfile and it'll install any other programs or setup any etc files for example if we ever need that. I'll probably make a PR for it later if you haven't already done this :)
